export enum PublicationErrorCode {
  PUBLICATION_TITLE_REQUIRED = 'PUBLICATION_TITLE_REQUIRED',
  PUBLICATION_TITLE_TOO_LONG = 'PUBLICATION_TITLE_TOO_LONG',
  PUBLICATION_CONTENT_REQUIRED = 'PUBLICATION_CONTENT_REQUIRED',
  PUBLICATION_CONTENT_TOO_LONG = 'PUBLICATION_CONTENT_TOO_LONG',
  PUBLICATION_AUTHOR_REQUIRED = 'PUBLICATION_AUTHOR_REQUIRED',
  PUBLICATION_NOT_FOUND = 'PUBLICATION_NOT_FOUND',
  PUBLICATION_NOT_OWNED = 'PUBLICATION_NOT_OWNED',
  PUBLICATION_UPDATE_EMPTY = 'PUBLICATION_UPDATE_EMPTY',
  PUBLICATION_FEED_PAGINATION_INVALID = 'PUBLICATION_FEED_PAGINATION_INVALID',
  PUBLICATION_FEED_FILTER_INVALID = 'PUBLICATION_FEED_FILTER_INVALID',
  PUBLICATION_MEDIA_URL_INVALID = 'PUBLICATION_MEDIA_URL_INVALID',
  PUBLICATION_MEDIA_URL_LIMIT_EXCEEDED = 'PUBLICATION_MEDIA_URL_LIMIT_EXCEEDED',
  PUBLICATION_COMMENT_CONTENT_REQUIRED = 'PUBLICATION_COMMENT_CONTENT_REQUIRED',
  PUBLICATION_COMMENT_CONTENT_TOO_LONG = 'PUBLICATION_COMMENT_CONTENT_TOO_LONG',
  PUBLICATION_COMMENT_AUTHOR_REQUIRED = 'PUBLICATION_COMMENT_AUTHOR_REQUIRED',
  PUBLICATION_COMMENT_NOT_FOUND = 'PUBLICATION_COMMENT_NOT_FOUND',
  PUBLICATION_COMMENT_NOT_OWNED = 'PUBLICATION_COMMENT_NOT_OWNED',
  PUBLICATION_REACTION_AUTHOR_REQUIRED = 'PUBLICATION_REACTION_AUTHOR_REQUIRED',
}

export class PublicationDomainError extends Error {
  public readonly code: PublicationErrorCode;
  public readonly details: Record<string, unknown>;

  constructor(
    code: PublicationErrorCode,
    message: string,
    details: Record<string, unknown> = {},
  ) {
    super(message);
    this.name = 'PublicationDomainError';
    this.code = code;
    this.details = details;
  }
}
