export class TrainerLinkDomainError extends Error {
  constructor(
    public readonly code: TrainerLinkErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'TrainerLinkDomainError';
  }
}

export const TrainerLinkErrorCode = {
  LINK_REQUEST_ALREADY_EXISTS: 'LINK_REQUEST_ALREADY_EXISTS',
  LINK_ALREADY_ACTIVE: 'LINK_ALREADY_ACTIVE',
  PENDING_REQUEST_EXISTS: 'PENDING_REQUEST_EXISTS',
  TRAINER_NOT_VERIFIED: 'TRAINER_NOT_VERIFIED',
  TRAINER_NOT_FOUND: 'TRAINER_NOT_FOUND',
  CLIENT_ACTIVE_LINK_LIMIT: 'CLIENT_ACTIVE_LINK_LIMIT',
  TRAINER_ACTIVE_CLIENT_LIMIT: 'TRAINER_ACTIVE_CLIENT_LIMIT',
  LINK_REQUEST_NOT_FOUND: 'LINK_REQUEST_NOT_FOUND',
  LINK_REQUEST_CANNOT_BE_CANCELLED: 'LINK_REQUEST_CANNOT_BE_CANCELLED',
  LINK_REQUEST_CANNOT_BE_ACCEPTED: 'LINK_REQUEST_CANNOT_BE_ACCEPTED',
  LINK_REQUEST_CANNOT_BE_REJECTED: 'LINK_REQUEST_CANNOT_BE_REJECTED',
  LINK_NOT_FOUND: 'LINK_NOT_FOUND',
  LINK_ALREADY_INACTIVE: 'LINK_ALREADY_INACTIVE',
  UNAUTHORIZED_LINK_ACCESS: 'UNAUTHORIZED_LINK_ACCESS',
  CANNOT_LINK_TO_SELF: 'CANNOT_LINK_TO_SELF',
} as const;

export type TrainerLinkErrorCode =
  (typeof TrainerLinkErrorCode)[keyof typeof TrainerLinkErrorCode];
