import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedExerciseCatalog1746000000010 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const exercises = [
      {
        id: '00000000-0000-4000-8000-000000000001',
        name: 'Press Banca',
        category: 'chest',
        primaryMuscleGroup: 'Pectoral Mayor',
        equipment: 'barbell',
        videoUrl: 'https://www.youtube.com/watch?v=4Y2ZdHCOXok',
        imageUrl: 'https://storage.endure.app/exercises/press-banca.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000002',
        name: 'Press Banca Inclinado',
        category: 'chest',
        primaryMuscleGroup: 'Pectoral Superior',
        equipment: 'barbell',
        videoUrl: 'https://www.youtube.com/watch?v=IP4oeKMx3VQ',
        imageUrl:
          'https://storage.endure.app/exercises/press-banca-inclinado.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000003',
        name: 'Aperturas con Mancuerna',
        category: 'chest',
        primaryMuscleGroup: 'Pectoral Mayor',
        equipment: 'dumbbell',
        videoUrl: 'https://www.youtube.com/watch?v=eozdVDA78K0',
        imageUrl:
          'https://storage.endure.app/exercises/aperturas-mancuerna.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000004',
        name: 'Sentadilla',
        category: 'legs',
        primaryMuscleGroup: 'Cuádriceps',
        equipment: 'barbell',
        videoUrl: 'https://www.youtube.com/watch?v=bEv6CCg2BC8',
        imageUrl: 'https://storage.endure.app/exercises/sentadilla.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000005',
        name: 'Sentadilla Frontal',
        category: 'legs',
        primaryMuscleGroup: 'Cuádriceps',
        equipment: 'barbell',
        videoUrl: 'https://www.youtube.com/watch?v=09duIahnWWI',
        imageUrl: 'https://storage.endure.app/exercises/sentadilla-frontal.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000006',
        name: 'Prensa de Piernas',
        category: 'legs',
        primaryMuscleGroup: 'Cuádriceps',
        equipment: 'machine',
        videoUrl: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
        imageUrl: 'https://storage.endure.app/exercises/prensa-piernas.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000007',
        name: 'Peso Muerto',
        category: 'back',
        primaryMuscleGroup: 'Espalda Baja',
        equipment: 'barbell',
        videoUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
        imageUrl: 'https://storage.endure.app/exercises/peso-muerto.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000008',
        name: 'Dominadas',
        category: 'back',
        primaryMuscleGroup: 'Dorsal Ancho',
        equipment: 'bodyweight',
        videoUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
        imageUrl: 'https://storage.endure.app/exercises/dominadas.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000009',
        name: 'Remo con Barra',
        category: 'back',
        primaryMuscleGroup: 'Dorsal Ancho',
        equipment: 'barbell',
        videoUrl: 'https://www.youtube.com/watch?v=FWJR5Ve8bnQ',
        imageUrl: 'https://storage.endure.app/exercises/remo-barra.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000010',
        name: 'Remo en Polea Baja',
        category: 'back',
        primaryMuscleGroup: 'Dorsal Ancho',
        equipment: 'cable',
        videoUrl: 'https://www.youtube.com/watch?v=xQNrMVMvXAE',
        imageUrl: 'https://storage.endure.app/exercises/remo-polea-baja.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000011',
        name: 'Press Militar',
        category: 'shoulders',
        primaryMuscleGroup: 'Deltoides',
        equipment: 'barbell',
        videoUrl: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
        imageUrl: 'https://storage.endure.app/exercises/press-militar.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000012',
        name: 'Elevaciones Laterales',
        category: 'shoulders',
        primaryMuscleGroup: 'Deltoides Laterales',
        equipment: 'dumbbell',
        videoUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
        imageUrl:
          'https://storage.endure.app/exercises/elevaciones-laterales.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000013',
        name: 'Curl de Bíceps con Barra',
        category: 'arms',
        primaryMuscleGroup: 'Bíceps',
        equipment: 'barbell',
        videoUrl: 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
        imageUrl: 'https://storage.endure.app/exercises/curl-biceps-barra.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000014',
        name: 'Curl Martillo',
        category: 'arms',
        primaryMuscleGroup: 'Bíceps',
        equipment: 'dumbbell',
        videoUrl: 'https://www.youtube.com/watch?v=zC3nLlVotJ8',
        imageUrl: 'https://storage.endure.app/exercises/curl-martillo.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000015',
        name: 'Extensiones de Tríceps en Polea',
        category: 'arms',
        primaryMuscleGroup: 'Tríceps',
        equipment: 'cable',
        videoUrl: 'https://www.youtube.com/watch?v=vB5OHsJ3eQE',
        imageUrl:
          'https://storage.endure.app/exercises/extensiones-triceps-polea.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000016',
        name: 'Fondos en Paralelas',
        category: 'chest',
        primaryMuscleGroup: 'Pectoral Mayor',
        equipment: 'bodyweight',
        videoUrl: 'https://www.youtube.com/watch?v=2z8JmcrW-As',
        imageUrl: 'https://storage.endure.app/exercises/fondos-paralelas.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000017',
        name: 'Plancha',
        category: 'core',
        primaryMuscleGroup: 'Abdominales',
        equipment: 'bodyweight',
        videoUrl: 'https://www.youtube.com/watch?v=ASdvN_XEl_c',
        imageUrl: 'https://storage.endure.app/exercises/plancha.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000018',
        name: 'Crunch Abdominal',
        category: 'core',
        primaryMuscleGroup: 'Abdominales',
        equipment: 'bodyweight',
        videoUrl: 'https://www.youtube.com/watch?v=Xyd_fa5zoEU',
        imageUrl: 'https://storage.endure.app/exercises/crunch-abdominal.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000019',
        name: 'Peso Muerto Rumano',
        category: 'legs',
        primaryMuscleGroup: 'Isquiotibiales',
        equipment: 'barbell',
        videoUrl: 'https://www.youtube.com/watch?v=7AaaYhMqmhY',
        imageUrl: 'https://storage.endure.app/exercises/peso-muerto-rumano.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000020',
        name: 'Curl de Piernas',
        category: 'legs',
        primaryMuscleGroup: 'Isquiotibiales',
        equipment: 'machine',
        videoUrl: 'https://www.youtube.com/watch?v=1Tq3QF6z5yY',
        imageUrl: 'https://storage.endure.app/exercises/curl-piernas.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000021',
        name: 'Elevación de Talones',
        category: 'legs',
        primaryMuscleGroup: 'Gemelos',
        equipment: 'machine',
        videoUrl: 'https://www.youtube.com/watch?v=YMmgE9h78WA',
        imageUrl: 'https://storage.endure.app/exercises/elevacion-talones.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000022',
        name: 'Face Pull',
        category: 'shoulders',
        primaryMuscleGroup: 'Deltoides Posterior',
        equipment: 'cable',
        videoUrl: 'https://www.youtube.com/watch?v=rep-qVOkqgk',
        imageUrl: 'https://storage.endure.app/exercises/face-pull.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000023',
        name: 'Swing de Pesa Rusa',
        category: 'legs',
        primaryMuscleGroup: 'Glúteos',
        equipment: 'kettlebell',
        videoUrl: 'https://www.youtube.com/watch?v=YSxHifyI6s8',
        imageUrl: 'https://storage.endure.app/exercises/swing-pesa-rusa.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000024',
        name: 'Carrera en Cinta',
        category: 'cardio',
        primaryMuscleGroup: 'Piernas',
        equipment: 'machine',
        videoUrl: null,
        imageUrl: 'https://storage.endure.app/exercises/carrera-cinta.jpg',
      },
      {
        id: '00000000-0000-4000-8000-000000000025',
        name: 'Burpees',
        category: 'cardio',
        primaryMuscleGroup: 'Cuerpo Completo',
        equipment: 'bodyweight',
        videoUrl: 'https://www.youtube.com/watch?v=auBLPXO8Fww',
        imageUrl: 'https://storage.endure.app/exercises/burpees.jpg',
      },
    ];

    for (const ex of exercises) {
      await queryRunner.query(
        `INSERT INTO exercise_catalog (id, name, category, "primaryMuscleGroup", equipment)
         VALUES ($1, $2, $3, $4, $5)
         ON CONFLICT (id) DO NOTHING`,
        [
          ex.id,
          ex.name,
          ex.category,
          ex.primaryMuscleGroup,
          ex.equipment,
        ],
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DELETE FROM exercise_catalog WHERE CAST(id AS TEXT) LIKE '00000000-0000-4000-8000-%'`,
    );
  }
}
