import { MigrationInterface, QueryRunner } from 'typeorm';

function tpl(n: number): string {
  return `00000000-0000-4000-8001-${String(n).padStart(12, '0')}`;
}

function ex(n: number): string {
  return `00000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
}

const CATALOG = {
  pressBancaPlano: ex(1),
  pressInclinadoManc: ex(5),
  aperturasPecDeck: ex(9),
  pulloverManc: ex(14),
  fondosParalelas: ex(15),
  dominadasPronas: ex(16),
  jalonPechoAbierto: ex(17),
  jalonPechoCerrado: ex(18),
  remoBarra: ex(19),
  remoPendlay: ex(20),
  remoManc1Mano: ex(21),
  remoPoleaBaja: ex(22),
  remoTBar: ex(23),
  pressMilitar: ex(31),
  pressHombroManc: ex(32),
  pressArnold: ex(33),
  pressHombroMaq: ex(34),
  elevLaterales: ex(35),
  elevLateralesPolea: ex(36),
  pajaros: ex(38),
  reversePecDeck: ex(39),
  facePulls: ex(40),
  curlBarraRecta: ex(43),
  curlZ: ex(44),
  curlAlterno: ex(45),
  curlMartillo: ex(46),
  curlPredicadorZ: ex(48),
  curlInclinado: ex(52),
  pressFrances: ex(55),
  extTricepsCuerda: ex(56),
  sentadillaLibre: ex(61),
  sentadillaFrontal: ex(62),
  sentadillaGoblet: ex(63),
  prensaPiernas: ex(66),
  extCuadriceps: ex(67),
  pesoMuertoRumano: ex(72),
  pesoMuertoPiernasRigidas: ex(73),
  curlFemoralAcostado: ex(74),
  curlFemoralSentado: ex(75),
  hipThrustBarra: ex(76),
  hipThrustMaq: ex(77),
  abduccionCadera: ex(79),
  talonesPie: ex(84),
  talonesSentado: ex(85),
  planchaFrontal: ex(88),
};

interface ExerciseSeed {
  catalogId: string;
  name: string;
  setsCount: number;
  initialReps: number;
  initialWeight: number;
}

interface TemplateSeed {
  id: string;
  experienceLevel: string;
  splitKey: string | null;
  name: string;
  dayOfWeek: string;
  displayOrder: number;
  exercises: ExerciseSeed[];
}

const TEMPLATES: TemplateSeed[] = [
  // ===== BEGINNER =====
  {
    id: tpl(1),
    experienceLevel: 'beginner',
    splitKey: null,
    name: 'Full Body A',
    dayOfWeek: 'monday',
    displayOrder: 1,
    exercises: [
      {
        catalogId: CATALOG.sentadillaLibre,
        name: 'Sentadilla libre con barra',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressBancaPlano,
        name: 'Press banca plano con barra',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.remoBarra,
        name: 'Remo con barra',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressMilitar,
        name: 'Press militar con barra',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.planchaFrontal,
        name: 'Plancha frontal',
        setsCount: 3,
        initialReps: 30,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(2),
    experienceLevel: 'beginner',
    splitKey: null,
    name: 'Full Body B',
    dayOfWeek: 'wednesday',
    displayOrder: 2,
    exercises: [
      {
        catalogId: CATALOG.prensaPiernas,
        name: 'Prensa de piernas',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressInclinadoManc,
        name: 'Press inclinado con mancuernas',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.jalonPechoAbierto,
        name: 'Jalón al pecho con agarre abierto',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.elevLaterales,
        name: 'Elevaciones laterales con mancuernas',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlZ,
        name: 'Curl con barra Z',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressFrances,
        name: 'Press francés con barra Z',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(3),
    experienceLevel: 'beginner',
    splitKey: null,
    name: 'Full Body C',
    dayOfWeek: 'friday',
    displayOrder: 3,
    exercises: [
      {
        catalogId: CATALOG.sentadillaGoblet,
        name: 'Sentadilla goblet con mancuerna',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.aperturasPecDeck,
        name: 'Aperturas en máquina pec deck',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.remoManc1Mano,
        name: 'Remo con mancuerna a una mano',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressHombroMaq,
        name: 'Press de hombro en máquina',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pesoMuertoRumano,
        name: 'Peso muerto rumano con barra',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
    ],
  },

  // ===== INTERMEDIATE =====
  {
    id: tpl(4),
    experienceLevel: 'intermediate',
    splitKey: null,
    name: 'Push A — Pecho',
    dayOfWeek: 'monday',
    displayOrder: 1,
    exercises: [
      {
        catalogId: CATALOG.pressBancaPlano,
        name: 'Press banca plano con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressInclinadoManc,
        name: 'Press inclinado con mancuernas',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.aperturasPecDeck,
        name: 'Aperturas en máquina pec deck',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressMilitar,
        name: 'Press militar con barra',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressFrances,
        name: 'Press francés con barra Z',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(5),
    experienceLevel: 'intermediate',
    splitKey: null,
    name: 'Pull A — Espalda densidad',
    dayOfWeek: 'tuesday',
    displayOrder: 2,
    exercises: [
      {
        catalogId: CATALOG.remoBarra,
        name: 'Remo con barra',
        setsCount: 4,
        initialReps: 8,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.remoPendlay,
        name: 'Remo Pendlay',
        setsCount: 3,
        initialReps: 8,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.dominadasPronas,
        name: 'Dominadas pronas',
        setsCount: 3,
        initialReps: 8,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pajaros,
        name: 'Pájaros con mancuernas',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlZ,
        name: 'Curl con barra Z',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(6),
    experienceLevel: 'intermediate',
    splitKey: null,
    name: 'Legs A — Cuádriceps',
    dayOfWeek: 'wednesday',
    displayOrder: 3,
    exercises: [
      {
        catalogId: CATALOG.sentadillaLibre,
        name: 'Sentadilla libre con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.prensaPiernas,
        name: 'Prensa de piernas',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.extCuadriceps,
        name: 'Extensión de cuádriceps',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlFemoralAcostado,
        name: 'Curl femoral acostado',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.talonesPie,
        name: 'Elevación de talones de pie',
        setsCount: 4,
        initialReps: 15,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(7),
    experienceLevel: 'intermediate',
    splitKey: null,
    name: 'Push B — Hombro + Tríceps',
    dayOfWeek: 'thursday',
    displayOrder: 4,
    exercises: [
      {
        catalogId: CATALOG.pressMilitar,
        name: 'Press militar con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.elevLaterales,
        name: 'Elevaciones laterales con mancuernas',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressHombroManc,
        name: 'Press de hombro con mancuernas',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.extTricepsCuerda,
        name: 'Extensión de tríceps en polea con cuerda',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressBancaPlano,
        name: 'Press banca plano con barra',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(8),
    experienceLevel: 'intermediate',
    splitKey: null,
    name: 'Pull B — Bíceps + Espalda volumen',
    dayOfWeek: 'friday',
    displayOrder: 5,
    exercises: [
      {
        catalogId: CATALOG.jalonPechoAbierto,
        name: 'Jalón al pecho con agarre abierto',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.remoPoleaBaja,
        name: 'Remo en polea baja',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.jalonPechoCerrado,
        name: 'Jalón al pecho con agarre cerrado',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlAlterno,
        name: 'Curl alterno con mancuernas',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlMartillo,
        name: 'Curl martillo',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.facePulls,
        name: 'Face pulls',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(9),
    experienceLevel: 'intermediate',
    splitKey: null,
    name: 'Legs B — Femoral + Pompis',
    dayOfWeek: 'saturday',
    displayOrder: 6,
    exercises: [
      {
        catalogId: CATALOG.pesoMuertoRumano,
        name: 'Peso muerto rumano con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.hipThrustBarra,
        name: 'Hip thrust con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlFemoralSentado,
        name: 'Curl femoral sentado',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.abduccionCadera,
        name: 'Abducción de cadera en máquina',
        setsCount: 3,
        initialReps: 15,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.sentadillaFrontal,
        name: 'Sentadilla frontal',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.talonesSentado,
        name: 'Elevación de talones sentado',
        setsCount: 4,
        initialReps: 15,
        initialWeight: 0,
      },
    ],
  },

  // ===== ADVANCED PPL (split_key='ppl') =====
  {
    id: tpl(10),
    experienceLevel: 'advanced',
    splitKey: 'ppl',
    name: 'Push A — Pecho',
    dayOfWeek: 'monday',
    displayOrder: 1,
    exercises: [
      {
        catalogId: CATALOG.pressBancaPlano,
        name: 'Press banca plano con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressInclinadoManc,
        name: 'Press inclinado con mancuernas',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.aperturasPecDeck,
        name: 'Aperturas en máquina pec deck',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressMilitar,
        name: 'Press militar con barra',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressFrances,
        name: 'Press francés con barra Z',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(11),
    experienceLevel: 'advanced',
    splitKey: 'ppl',
    name: 'Pull A — Espalda densidad',
    dayOfWeek: 'tuesday',
    displayOrder: 2,
    exercises: [
      {
        catalogId: CATALOG.remoBarra,
        name: 'Remo con barra',
        setsCount: 4,
        initialReps: 8,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.remoPendlay,
        name: 'Remo Pendlay',
        setsCount: 3,
        initialReps: 8,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.dominadasPronas,
        name: 'Dominadas pronas',
        setsCount: 3,
        initialReps: 8,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pajaros,
        name: 'Pájaros con mancuernas',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlZ,
        name: 'Curl con barra Z',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(12),
    experienceLevel: 'advanced',
    splitKey: 'ppl',
    name: 'Legs A — Cuádriceps',
    dayOfWeek: 'wednesday',
    displayOrder: 3,
    exercises: [
      {
        catalogId: CATALOG.sentadillaLibre,
        name: 'Sentadilla libre con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.prensaPiernas,
        name: 'Prensa de piernas',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.extCuadriceps,
        name: 'Extensión de cuádriceps',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlFemoralAcostado,
        name: 'Curl femoral acostado',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.talonesPie,
        name: 'Elevación de talones de pie',
        setsCount: 4,
        initialReps: 15,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(13),
    experienceLevel: 'advanced',
    splitKey: 'ppl',
    name: 'Push B — Hombro + Tríceps',
    dayOfWeek: 'thursday',
    displayOrder: 4,
    exercises: [
      {
        catalogId: CATALOG.pressMilitar,
        name: 'Press militar con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.elevLaterales,
        name: 'Elevaciones laterales con mancuernas',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressHombroManc,
        name: 'Press de hombro con mancuernas',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.extTricepsCuerda,
        name: 'Extensión de tríceps en polea con cuerda',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressBancaPlano,
        name: 'Press banca plano con barra',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(14),
    experienceLevel: 'advanced',
    splitKey: 'ppl',
    name: 'Pull B — Bíceps + Espalda volumen',
    dayOfWeek: 'friday',
    displayOrder: 5,
    exercises: [
      {
        catalogId: CATALOG.jalonPechoAbierto,
        name: 'Jalón al pecho con agarre abierto',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.remoPoleaBaja,
        name: 'Remo en polea baja',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.jalonPechoCerrado,
        name: 'Jalón al pecho con agarre cerrado',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlAlterno,
        name: 'Curl alterno con mancuernas',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlMartillo,
        name: 'Curl martillo',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.facePulls,
        name: 'Face pulls',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(15),
    experienceLevel: 'advanced',
    splitKey: 'ppl',
    name: 'Legs B — Femoral + Pompis',
    dayOfWeek: 'saturday',
    displayOrder: 6,
    exercises: [
      {
        catalogId: CATALOG.pesoMuertoRumano,
        name: 'Peso muerto rumano con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.hipThrustBarra,
        name: 'Hip thrust con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlFemoralSentado,
        name: 'Curl femoral sentado',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.abduccionCadera,
        name: 'Abducción de cadera en máquina',
        setsCount: 3,
        initialReps: 15,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.sentadillaFrontal,
        name: 'Sentadilla frontal',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.talonesSentado,
        name: 'Elevación de talones sentado',
        setsCount: 4,
        initialReps: 15,
        initialWeight: 0,
      },
    ],
  },

  // ===== ADVANCED ARNOLD (split_key='arnold') =====
  {
    id: tpl(16),
    experienceLevel: 'advanced',
    splitKey: 'arnold',
    name: 'Chest+Back A — Pecho',
    dayOfWeek: 'monday',
    displayOrder: 1,
    exercises: [
      {
        catalogId: CATALOG.pressBancaPlano,
        name: 'Press banca plano con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressInclinadoManc,
        name: 'Press inclinado con mancuernas',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.aperturasPecDeck,
        name: 'Aperturas en máquina pec deck',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.dominadasPronas,
        name: 'Dominadas pronas',
        setsCount: 3,
        initialReps: 8,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.remoBarra,
        name: 'Remo con barra',
        setsCount: 3,
        initialReps: 8,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(17),
    experienceLevel: 'advanced',
    splitKey: 'arnold',
    name: 'Shoulders+Arms A — Hombros',
    dayOfWeek: 'tuesday',
    displayOrder: 2,
    exercises: [
      {
        catalogId: CATALOG.pressMilitar,
        name: 'Press militar con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.elevLaterales,
        name: 'Elevaciones laterales con mancuernas',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pajaros,
        name: 'Pájaros con mancuernas',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlBarraRecta,
        name: 'Curl con barra recta',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressFrances,
        name: 'Press francés con barra Z',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(18),
    experienceLevel: 'advanced',
    splitKey: 'arnold',
    name: 'Legs A — Cuádriceps',
    dayOfWeek: 'wednesday',
    displayOrder: 3,
    exercises: [
      {
        catalogId: CATALOG.sentadillaLibre,
        name: 'Sentadilla libre con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.prensaPiernas,
        name: 'Prensa de piernas',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.extCuadriceps,
        name: 'Extensión de cuádriceps',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlFemoralAcostado,
        name: 'Curl femoral acostado',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.talonesPie,
        name: 'Elevación de talones de pie',
        setsCount: 4,
        initialReps: 15,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(19),
    experienceLevel: 'advanced',
    splitKey: 'arnold',
    name: 'Chest+Back B — Espalda',
    dayOfWeek: 'thursday',
    displayOrder: 4,
    exercises: [
      {
        catalogId: CATALOG.dominadasPronas,
        name: 'Dominadas pronas',
        setsCount: 4,
        initialReps: 8,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.remoPendlay,
        name: 'Remo Pendlay',
        setsCount: 4,
        initialReps: 8,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.remoPoleaBaja,
        name: 'Remo en polea baja',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pulloverManc,
        name: 'Pullover con mancuerna',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressBancaPlano,
        name: 'Press banca plano con barra',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(20),
    experienceLevel: 'advanced',
    splitKey: 'arnold',
    name: 'Shoulders+Arms B — Brazos',
    dayOfWeek: 'friday',
    displayOrder: 5,
    exercises: [
      {
        catalogId: CATALOG.curlZ,
        name: 'Curl con barra Z',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.extTricepsCuerda,
        name: 'Extensión de tríceps en polea con cuerda',
        setsCount: 4,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlMartillo,
        name: 'Curl martillo',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.pressArnold,
        name: 'Press Arnold',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.elevLateralesPolea,
        name: 'Elevaciones laterales en polea',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
    ],
  },
  {
    id: tpl(21),
    experienceLevel: 'advanced',
    splitKey: 'arnold',
    name: 'Legs B — Femoral + Pompis',
    dayOfWeek: 'saturday',
    displayOrder: 6,
    exercises: [
      {
        catalogId: CATALOG.pesoMuertoRumano,
        name: 'Peso muerto rumano con barra',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.hipThrustMaq,
        name: 'Hip thrust en máquina',
        setsCount: 4,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.curlFemoralSentado,
        name: 'Curl femoral sentado',
        setsCount: 3,
        initialReps: 12,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.abduccionCadera,
        name: 'Abducción de cadera en máquina',
        setsCount: 3,
        initialReps: 15,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.sentadillaFrontal,
        name: 'Sentadilla frontal',
        setsCount: 3,
        initialReps: 10,
        initialWeight: 0,
      },
      {
        catalogId: CATALOG.talonesSentado,
        name: 'Elevación de talones sentado',
        setsCount: 4,
        initialReps: 15,
        initialWeight: 0,
      },
    ],
  },
];

export class SeedDefaultRoutineTemplates1776000000001 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const tpl of TEMPLATES) {
      await queryRunner.query(
        `INSERT INTO default_routine_templates (id, experience_level, split_key, name, day_of_week, display_order)
         VALUES ($1, $2, $3, $4, $5, $6)
         ON CONFLICT (id) DO NOTHING`,
        [
          tpl.id,
          tpl.experienceLevel,
          tpl.splitKey,
          tpl.name,
          tpl.dayOfWeek,
          tpl.displayOrder,
        ],
      );

      for (let i = 0; i < tpl.exercises.length; i++) {
        const ex = tpl.exercises[i];
        await queryRunner.query(
          `INSERT INTO default_routine_template_exercises (id, template_id, exercise_catalog_id, exercise_name, exercise_order, sets_count, initial_reps, initial_weight)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
           ON CONFLICT (id) DO NOTHING`,
          [
            crypto.randomUUID(),
            tpl.id,
            ex.catalogId,
            ex.name,
            i + 1,
            ex.setsCount,
            ex.initialReps,
            ex.initialWeight,
          ],
        );
      }
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DELETE FROM default_routine_template_exercises`);
    await queryRunner.query(`DELETE FROM default_routine_templates`);
  }
}
