export class TrainerVerificationDomainError extends Error {
  constructor(
    public readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = 'TrainerVerificationDomainError';
  }
}

export const TrainerVerificationErrorCode = {
  VERIFICATION_ALREADY_EXISTS: 'VERIFICATION_ALREADY_EXISTS',
  VERIFICATION_NOT_FOUND: 'VERIFICATION_NOT_FOUND',
  VERIFICATION_NOT_REJECTED: 'VERIFICATION_NOT_REJECTED',
  VERIFICATION_ALREADY_APPROVED: 'VERIFICATION_ALREADY_APPROVED',
  INVALID_SPECIALTY_KEY: 'INVALID_SPECIALTY_KEY',
  TOO_MANY_SPECIALTIES: 'TOO_MANY_SPECIALTIES',
  TOO_FEW_SPECIALTIES: 'TOO_FEW_SPECIALTIES',
  INVALID_YEARS_OF_EXPERIENCE: 'INVALID_YEARS_OF_EXPERIENCE',
  BIO_TOO_LONG: 'BIO_TOO_LONG',
  ID_DOCUMENT_NUMBER_REQUIRED: 'ID_DOCUMENT_NUMBER_REQUIRED',
  TOO_MANY_ID_DOCUMENTS: 'TOO_MANY_ID_DOCUMENTS',
  TOO_FEW_ID_DOCUMENTS: 'TOO_FEW_ID_DOCUMENTS',
  TOO_MANY_CERTIFICATES: 'TOO_MANY_CERTIFICATES',
  TOO_FEW_CERTIFICATES: 'TOO_FEW_CERTIFICATES',
  INVALID_CERTIFICATE: 'INVALID_CERTIFICATE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  REJECTION_REASON_REQUIRED: 'REJECTION_REASON_REQUIRED',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  NOT_TRAINER_ROLE: 'NOT_TRAINER_ROLE',
  NOT_ADMIN_ROLE: 'NOT_ADMIN_ROLE',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  AUDIT_EVENT_NOT_FOUND: 'AUDIT_EVENT_NOT_FOUND',
  INVALID_DRAFT_OPERATION: 'INVALID_DRAFT_OPERATION',
  ALREADY_ASSIGNED: 'ALREADY_ASSIGNED',
  NOT_ASSIGNED_TO_YOU: 'NOT_ASSIGNED_TO_YOU',
  CORRECTION_MESSAGE_REQUIRED: 'CORRECTION_MESSAGE_REQUIRED',
} as const;

export type TrainerVerificationErrorCode =
  (typeof TrainerVerificationErrorCode)[keyof typeof TrainerVerificationErrorCode];
