name: Backend CI

on:
  push:
    branches: [master, develop, dev]
  pull_request:
    branches: [master]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.projectKey=enduren-back
            -Dsonar.sources=src
        env:
          SONAR_TOKEN: squ_f8efac174584cb4f0aa1e7a07b9420c500e75c52
          SONAR_HOST_URL: https://kindling-obstacle-freebie.ngrok-free.dev
